df_cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart),
    url(r'^add(\d+)_(\d+)/$', views.add),
    url(r'^edit(\d+)_(\d+)$', views.edit),
    url(r'^delete(\d+)/$', views.delete),
    url(r'^edit(\d+)_(\d+)/$', views.edit)
]

df_user/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


urlpatterns = [
    path('register/', views.register),
    path('register_handle/', views.register_handle),
    path('login/', views.login),
    path('login_handle/', views.login_handle),
    path('info/', views.info),
    # path('order(\d+)/', views.order),
    url(r'^order/$', views.order),
    path('site/', views.site),
    path('register_exist/', views.register_exist),
    path('logout/', views.logout),
    path('verifyCode', views.verifyCode)
]

graduation_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('df_user.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('goods/', include('df_goods.urls')),
    path('cart/', include('df_cart.urls')),
    path('order/', include('df_order.urls')),
    path('', include('df_search.urls'))
    # path('search/', include('haystack.urls')),
]

df_order/models.py
from django.db import models


class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey('df_user.UserInfo', on_delete=models.CASCADE)
    odate = models.DateTimeField(auto_now=True)
    oIsPay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=8, decimal_places=2)
    oaddress = models.CharField(max_length=200)
#无法实现：真是支付、物流信息

class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo', on_delete=models.CASCADE)
    order = models.ForeignKey(OrderInfo, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    count = models.IntegerField()

df_user/models.py
from django.db import models


class UserInfo(models.Model):
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=30)
    ushou = models.CharField(max_length=20, default='')
    uaddress = models.CharField(max_length=100, default='')
    uyoubian = models.CharField(max_length=6, default='')
    uphone = models.CharField(max_length=11, default='')
    '''default, blank是python层面的约束，不影响数据库表结构'''

df_user/views.py
from django.shortcuts import render, redirect
from .models import *
from hashlib import sha1
from django.http import JsonResponse, HttpResponseRedirect
from . import user_decorator
from df_goods.models import GoodsInfo
from df_order.models import *
from django.core.paginator import Paginator, Page
from hashlib import sha1
from .redisHelper import redisHelper
from django.http import HttpResponse



'''验证码'''
def verifyCode(request):
    from PIL import Image, ImageDraw, ImageFont
    import random
    # 创建背景颜色
    bgColor = (random.randrange(50, 100), random.randrange(50, 100), 0)
    # 规定宽高
    # width = 100
    # height = 25
    width = 120
    height = 30
    # 创建画布
    image = Image.new('RGB', (width, height), bgColor)
    # 构造字体对象
    font = ImageFont.truetype('arial.ttf', 22)
    # 创建画笔
    draw = ImageDraw.Draw(image)
    # 创建文本内容
    text = '0123456789ABCDEFGHIGKLMNOPQRSTUVWSYZ'
    # 逐个绘制字符
    textTemp = ''
    for i in range(4):
        textTemp1 = text[random.randrange(0, len(text))]
        textTemp += textTemp1
        draw.text(
            (i*30, 0),
            textTemp1,
            (255, 255, 255),
            font
        )

    request.session['code'] = textTemp
    # 保存到内存流中
    import io
    buf = io.BytesIO()
    image.save(buf, 'png')
    # 将内存流中的内容输出到客户端
    return HttpResponse(buf.getvalue(), 'image/png')


def register(request):
    return render(request, 'df_user/register.html')



def register_handle(request):
    #接受用户输入
    post = request.POST
    uname = post.get('user_name')
    upwd = post.get('pwd')
    upwd2 = post.get('cpwd')
    uemail = post.get('email')
    code1 = post.get('code1').lower()
    code2 = request.session['code']
    code3 = code2.lower()

    #判断验证码是否正确
    if code1 != code3:

        return redirect('/user/register')

    #判断俩次密码
    if upwd != upwd2:
        return redirect('/user/register')

    #判断用户名是否存在
    count = UserInfo.objects.filter(uname=uname).count()
    if count == 1:
        return redirect('/user/register')


    #密码加密
    s1 = sha1()
    s1.update(upwd.encode("utf8"))
    upwd3 = s1.hexdigest()

    #创建对象
    user = UserInfo()
    user.uname = uname
    user.upwd = upwd3
    user.uemail = uemail
    user.save()
    #注册成功，转到登录页面
    return redirect('/user/login/')


def register_exist(request):
    uname = request.GET.get('uname')
    count = UserInfo.objects.filter(uname=uname).count()

    return JsonResponse({'count': count})


def login(request):
    uname = request.COOKIES.get('uname', '')
    context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 0, 'uname': uname}
    return render(request, 'df_user/login.html', context)


def login_handle(request):
    #接受请求数据
    post = request.POST
    uname = post.get('username')
    upwd = post.get('pwd')
    jizhu = post.get('jizhu', 0)
    #根据用户名查询对象
    users = UserInfo.objects.filter(uname=uname)#[]
    # print(uname)
    #判断：如果未查到则用户名错误，如果查到则判断密码是否正确，正确则转到用户中心
    # if len(users) == 1:
    #     s1 = sha1()
    #     s1.update(upwd.encode("utf8"))
    #     if s1.hexdigest() == users[0].upwd:
    #         red = HttpResponseRedirect('/user/info/')
    #         #记住用户名
    #         if jizhu != 0:
    #             red.set_cookie('uname', uname)
    #         else:
    #             red.set_cookie('uname', '', max_age=-1)
    #         request.session['user_id'] = users[0].id
    #         request.session['user_name'] = uname
    #         return red
    #     else:
    #         context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1, 'uname': uname, 'upwd': upwd}
    #         return render(request, 'df_user/login.html', context)
    # else:
    #     context = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname, 'upwd': upwd}
    #     return render(request, 'df_user/login.html', context)



    r = redisHelper('172.27.0.6', 6379)

    if r.get(uname)==None:


        if len(users) == 1:
            s1 = sha1()
            s1.update(upwd.encode("utf8"))
            if s1.hexdigest() == users[0].upwd:
                red = HttpResponseRedirect('/user/info/')
                #记住用户名
                if jizhu != 0:
                    red.set_cookie('uname', uname)
                else:
                    red.set_cookie('uname', '', max_age=-1)
                request.session['user_id'] = users[0].id
                request.session['user_name'] = uname
                r.set(uname, users[0].upwd)
                return red
            else:
                context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1, 'uname': uname, 'upwd': upwd}
                return render(request, 'df_user/login.html', context)
        else:
            context = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname, 'upwd': upwd}
            return render(request, 'df_user/login.html', context)


    else:
        s1 = sha1()
        s1.update(upwd.encode("utf8"))
        if r.get(uname).decode() == s1.hexdigest():
            red = HttpResponseRedirect('/user/info/')
            # 记住用户名
            if jizhu != 0:
                red.set_cookie('uname', uname)
            else:
                red.set_cookie('uname', '', max_age=-1)
            request.session['user_id'] = users[0].id
            request.session['user_name'] = uname
            r.set(uname, users[0].upwd)
            return red
        else:
            context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1, 'uname': uname, 'upwd': upwd}
            return render(request, 'df_user/login.html', context)



def logout(request):
    request.session.flush()
    return redirect('/user/login/')


@user_decorator.login
def info(request):
    user_email = UserInfo.objects.get(id=request.session['user_id']).uemail
    user_address = UserInfo.objects.get(id=request.session['user_id']).uaddress
    #最近浏览
    goods_ids = request.COOKIES.get('goods_ids', '')
    goods_ids1 = goods_ids.split(',')

    # GoodsInfo.objects.filter(id__in=goods_ids1) #可以查出来商品信息，但不能维护顺序

    good_list = []
    for goods_id in goods_ids1:
        if goods_id != '':
            good_list.append(GoodsInfo.objects.get(id=int(goods_id)))
    context = {
        'title': '用户中心',
        'user_email': user_email,
        'user_address': user_address,
        'user_name': request.session['user_name'],
        'page_name': 1,
        'goods_list': good_list
    }
    return render(request, 'df_user/user_center_info.html', context)


@user_decorator.login
def order(request):
    order = OrderInfo.objects.filter(user_id=request.session['user_id'])
    # order1 = OrderDetailInfo.objects.filter(order_id=order.oid)

    orderdetail = OrderDetailInfo.objects.all()

    # paginator = Paginator(order, 1)
    # page = paginator.page(int(pindex))
    context = {'title': '用户中心',
               'page_name': 1,
               'order': order,
               'orderdetail': orderdetail,
               # 'Page': page,
               # 'paginator': paginator
               }
    return render(request, 'df_user/user_center_order.html', context)


@user_decorator.login
def site(request):
    user = UserInfo.objects.get(id=request.session['user_id'])
    if request.method == 'POST':
        post = request.POST
        user.ushou = post.get('ushou')
        user.uaddress = post.get('uaddress')
        user.uyoubian = post.get('uyoubian')
        user.uphone = post.get('uphone')
        user.save()
    context = {'title': '用户中心', 'user': user, 'page_name': 1}
    return render(request, 'df_user/user_center_site.html', context)

templates/df_user/login.html
{% extends 'base_foot.html' %}
{% block head %}
    <script>
    $(function () {
        name_error = false;
        pwd_error = false;

        if({{ error_name }}==1){
            $('.user_error').html('用户名错误').show();
        }

        if({{ error_pwd }}==1){
            $('.pwd_error').html('密码错误').show()
        }

        $('.name_input').blur(function () {
            if($('.name_input').val().length==0){
                $('.user_error').html('请填写用户名').show();
                name_error=false
            }else {
                $('.user_error').hide();
                name_error=true;
            }
        });

        $('.pass_input').blur(function () {
            if($(this).val().length==0){
                $('.pwd_error').html('请输入密码').show();
                pwd_error=false
            }else {
                $('.pwd_error').hide();
                pwd_error=true;
            }
        });

        $('from').submit(function () {

        })
    })
    </script>
{% endblock head %}


{% block body %}
	<div class="login_top clearfix">
		<a href="/goods/" class="login_logo"><img src="/static/images_1/school_log5.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">资源共享 · 互助无偿</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handle/" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ uname }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{ upwd }}" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>

						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock body %}

templates/df_user/register.html
{% extends 'base_foot.html' %}

{% block head %}
<script type="text/javascript" src="/static/js/register.js"></script>

{% endblock head %}

{% block body %}
<body>
	<div class="register_con">
		<div class="l_con fl">
{#			<a class="reg_logo"><img src="/static/images/logo02.png"></a>#}
            <a href="/goods/" class="reg_logo"><img src="/static/images_1/school_log5.png"></a>
			<div class="reg_slogan">足不出户  ·  共享每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_handle/", method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>


                    <li>
						<label>验证码:</label>
                        <img src="/user/verifyCode">
						<input type="text" name="code1" id="code1">
						<span class="error_tip">提示信息</span>
					</li>


					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”校园共享用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{% endblock body %}

templates/df_user/user_center_info.html
{% extends 'base.html' %}

{% block body1 %}
<body>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info" class="active">· 个人信息</a></li>
				<li><a href="/user/order">· 全部订单</a></li>
				<li><a href="/user/site">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user_name }}</li>
							<li><span>电子邮箱：</span>{{ user_email }}</li>
							<li><span>联系地址：</span>{{ user_address }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
                    <ul class="goods_type_list clearfix">

                {% if goods_list != '' %}
                    {% for g in goods_list %}
                        <li>
                            <a href="/goods/{{ g.id }}"><img src="/static/{{ g.gpic }}"></a>
                            <h4><a href="/goods/{{ g.id }}">{{ g.gtitle }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ g.gprice }}</span>
                                <span class="unit">{{ g.gunit }}</span>
                                <a href="/cart/add{{ g.id }}_1/" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                    {% endfor %}
                {% endif %}
			</ul>
		</div>
		</div>
	</div>
{% endblock body1 %}

templates/df_user/user_center_order.html
{% extends 'base.html' %}

{% block body1 %}
<body>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info">· 个人信息</a></li>
				<li><a href="/user/order" class="active">· 全部订单</a></li>
				<li><a href="/user/site">· 收货地址</a></li>
			</ul>
		</div>

		<div class="right_content clearfix">
        <h3 class="common_title2">全部订单</h3>


            {% for o in order %}

				<ul class="order_list_th w978 clearfix">

					<li class="col01">{{ o.odate }}</li>
					<li class="col02">{{ o.oid }}</li>
                    {% if o.oIsPay|default:''%}
                        <li class="col02 stress">已支付</li>
                            {% else %}
                            <li class="col02 stress">未支付</li>
                    {% endif %}
                </ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">
                                    {% for o1 in o.orderdetailinfo_set.all %}
                                        <li class="col01"><a href="/goods/{{ o1.goods.id }}"><img src="/static/{{ o1.goods.gpic }}"></a></li>
									<li class="col02">{{ o1.goods.gtitle }}<em>{{ o1.goods.gprice }}/{{ o1.goods.gunit }}</em></li>
									<li class="col03">{{ o1.count }}</li>
									<li class="col04">{{ o1.goods.gprice }}</li>
                                    {% endfor %}
								</ul>

							</td>
							<td width="15%">{{ o.ototal }}</td>
                        {% if o.oIsPay|default:'' %}
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                            {% else %}
                            <td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						{% endif %}
                        </tr>
					</tbody>
				</table>

{#				<ul class="order_list_th w978 clearfix">#}
{#					<li class="col01">2016-8-21 17:36:24</li>#}
{#					<li class="col02">订单号：56872934</li>#}
{#					<li class="col02 stress">已支付</li>			#}
{#				</ul>#}
{#				<table class="order_list_table w980">#}
{#					<tbody>#}
{#						<tr>#}
{#							<td width="55%">#}
{#                                {% for o in order %}#}
{#								<ul class="order_goods_list clearfix">					#}
{#									<li class="col01"><img src="/static/{{ o.goods. }}"></li>#}
{#									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	#}
{#									<li class="col03">1</li>#}
{#									<li class="col04">11.80元</li>	#}
{#								</ul>#}
{#                                {% endfor %}#}
{#							</td>#}
{#							<td width="15%">33.60元</td>#}
{#							<td width="15%">已付款</td>#}
{#							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>#}
{#						</tr>#}
{#					</tbody>#}
{#				</table>#}

        {% endfor %}

{#        <div class="pagenation">#}
{#                {% if page.has_previous %}#}
{#				<a href="/user/order_{{ page.previous_page_number }}">上一页</a>#}
{#                {% endif %}#}
{##}
{#                {% for pindex in paginator.page_range %}#}
{#                {% if pindex == page.number %}#}
{#                <a href="#" class="active">{{ pindex }}</a>#}
{#                {% else %}#}
{#                <a href="/user/order_{{ pindex }}/">{{ pindex }}</a>#}
{#                {% endif %}#}
{#                {% endfor %}#}
{##}
{#                {% if page.has_next %}#}
{#                <a href="/goods/list_{{ page.next_page_number }}">下一页</a>#}
{#                {% endif %}#}
{##}
{#			</div>#}
        </div>
    </div>
{% endblock body1 %}

templates/df_user/user_center_site.html
{% extends 'base.html' %}

{% block body1 %}
<body>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info">· 个人信息</a></li>
				<li><a href="/user/order">· 全部订单</a></li>
				<li><a href="/user/site" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.ushou }} （{{ user.uname }} 收） {{ user.uphone }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form  method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收货地址：</label>
							<input type="text" name="ushou">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="uyoubian">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock body1 %}